# Generated by ChatGPT for AI support/operator monitoring.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seed_ai_demo_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='operator_reply_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='topic',
            field=models.CharField(blank=True, db_index=True, default='general', max_length=60),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
