from django.db import migrations


MORE_PRODUCTS = [
    # Telefonlar
    {
        'title': 'Xiaomi Redmi Note 13',
        'img': 'products/iphone-16-pro.svg',
        'review': 4,
        'description': 'Xiaomi Redmi Note 13 — arzon narxda yaxshi kamera va kuchli batareya. Kundalik foydalanish, ijtimoiy tarmoqlar, video va musiqa uchun ajoyib tanlov. RAM: 8GB, xotira: 256GB.',
        'price': 3490000,
        'old_price': 3990000,
        'author': 'AZIKO MARKET',
        'category': 'telefon',
        'color': 'ko\'k',
        'sizes': '128GB, 256GB',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 65,
    },
    {
        'title': 'iPhone 15',
        'img': 'products/iphone-16-pro.svg',
        'review': 5,
        'description': 'Apple iPhone 15 — oldingi versiyadan arzonroq, lekin sifat saqlanib qolgan. Dynamic Island, 48MP kamera, USB-C port. iOS ekotizimiga kirish uchun qulay narx.',
        'price': 13500000,
        'old_price': None,
        'author': 'AZIKO MARKET',
        'category': 'telefon',
        'color': 'oq',
        'sizes': '128GB, 256GB',
        'in_stock': True,
        'is_discount': False,
        'sold_count': 41,
    },
    {
        'title': 'Samsung Galaxy A55',
        'img': 'products/samsung-s25-ultra.svg',
        'review': 4,
        'description': 'Samsung Galaxy A55 — o\'rta segment flagman. Yaxshi kamera, sifatli ekran, uzoq ishlash vaqti. Instagram, TikTok, foto va kundalik ishlar uchun mos.',
        'price': 5200000,
        'old_price': 5800000,
        'author': 'AZIKO MARKET',
        'category': 'telefon',
        'color': 'ko\'k',
        'sizes': '128GB, 256GB',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 58,
    },
    # Noutbuklar
    {
        'title': 'ASUS VivoBook 15',
        'img': 'products/macbook-pro.svg',
        'review': 4,
        'description': 'ASUS VivoBook 15 — o\'qish va ofis ishi uchun ideal noutbuk. Yengil korpus, 15.6 dyuym ekran, Intel Core i5, 16GB RAM, 512GB SSD. Talabalar va ish yuklamalari uchun qulay.',
        'price': 8900000,
        'old_price': 9500000,
        'author': 'AZIKO MARKET',
        'category': 'noutbuk',
        'color': 'kulrang',
        'sizes': '15.6 dyuym',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 27,
    },
    {
        'title': 'Lenovo IdeaPad 3',
        'img': 'products/macbook-pro.svg',
        'review': 4,
        'description': 'Lenovo IdeaPad 3 — arzon narxda ishonchli noutbuk. AMD Ryzen 5, 8GB RAM, 256GB SSD. Oddiy o\'qish, video ko\'rish va ofis dasturlari uchun yetarli.',
        'price': 5500000,
        'old_price': None,
        'author': 'AZIKO MARKET',
        'category': 'noutbuk',
        'color': 'ko\'k',
        'sizes': '14 dyuym',
        'in_stock': True,
        'is_discount': False,
        'sold_count': 33,
    },
    {
        'title': 'HP Pavilion Gaming',
        'img': 'products/macbook-pro.svg',
        'review': 5,
        'description': 'HP Pavilion Gaming — o\'yin va grafik ishlar uchun kuchli noutbuk. NVIDIA GTX 1650, Intel Core i7, 16GB RAM, 512GB SSD. GTA, CS2, Valorant ishlatishga tayyor.',
        'price': 13200000,
        'old_price': 14500000,
        'author': 'AZIKO MARKET',
        'category': 'noutbuk',
        'color': 'qora',
        'sizes': '15.6 dyuym',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 19,
    },
    # Quloqchinlar
    {
        'title': 'JBL Tune 510BT',
        'img': 'products/black-earbuds.svg',
        'review': 4,
        'description': 'JBL Tune 510BT — JBL Pure Bass tovush sifati bilan quloq ustiga qo\'yiladigan simsiz quloqchin. 40 soat batareya, yengil dizayn, sport va kundalik foydalanish uchun.',
        'price': 399000,
        'old_price': 480000,
        'author': 'AZIKO MARKET',
        'category': 'quloqchin',
        'color': 'qora',
        'sizes': 'universal',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 89,
    },
    {
        'title': 'Samsung Galaxy Buds2',
        'img': 'products/white-minipods.svg',
        'review': 4,
        'description': 'Samsung Galaxy Buds2 — ANC (shovqin kamaytirish) funksiyali in-ear quloqchin. Yengil, ixcham, Samsung telefonlar bilan yaxshi ishlaydi. Kundalik foydalanish va qo\'ng\'iroq uchun.',
        'price': 750000,
        'old_price': 890000,
        'author': 'AZIKO MARKET',
        'category': 'quloqchin',
        'color': 'oq',
        'sizes': 'universal',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 47,
    },
    {
        'title': 'Anker Soundcore Q20i',
        'img': 'products/black-earbuds.svg',
        'review': 4,
        'description': 'Anker Soundcore Q20i — ANC funksiyali arzon quloqchin. 60 soat batareya, quloq ustiga qo\'yiladigan, shovqin kamaytirish bor. O\'qish, ish va sayohat uchun ajoyib tanlov.',
        'price': 280000,
        'old_price': None,
        'author': 'AZIKO MARKET',
        'category': 'quloqchin',
        'color': 'qora',
        'sizes': 'universal',
        'in_stock': True,
        'is_discount': False,
        'sold_count': 102,
    },
    # Televizorlar
    {
        'title': 'Samsung Crystal UHD 43',
        'img': 'products/smart-tv-lg.svg',
        'review': 4,
        'description': 'Samsung Crystal UHD 43" — 4K ekranli Smart TV. YouTube, Netflix, kino ko\'rish uchun ideal. Kichikroq xona va yotoqxona uchun mos o\'lcham.',
        'price': 4200000,
        'old_price': 4800000,
        'author': 'AZIKO MARKET',
        'category': 'televizor',
        'color': 'qora',
        'sizes': '43 dyuym',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 38,
    },
    {
        'title': 'LG OLED evo C3 65',
        'img': 'products/smart-tv-lg.svg',
        'review': 5,
        'description': 'LG OLED evo C3 65" — premium OLED Smart TV. Mukammal rang sifati, HDR, Dolby Atmos, gaming rejimi. Kino, sport va o\'yin uchun eng yaxshi tanlov.',
        'price': 18500000,
        'old_price': None,
        'author': 'AZIKO MARKET',
        'category': 'televizor',
        'color': 'qora',
        'sizes': '65 dyuym',
        'in_stock': True,
        'is_discount': False,
        'sold_count': 12,
    },
    # Krossovkalar
    {
        'title': 'Nike Air Max 90',
        'img': 'products/black-sneakers.svg',
        'review': 5,
        'description': 'Nike Air Max 90 — klassik sport krossovkasi. Air Max yostiqchasi, qulay taglik, sport va kundalik kiyim uchun mos. Har qanday kiyim uslubiga tushadi.',
        'price': 890000,
        'old_price': 990000,
        'author': 'AZIKO MARKET',
        'category': 'krossovka',
        'color': 'oq',
        'sizes': '38, 39, 40, 41, 42, 43, 44',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 55,
    },
    {
        'title': 'Adidas Ultraboost 22',
        'img': 'products/black-sneakers.svg',
        'review': 5,
        'description': 'Adidas Ultraboost 22 — yugurish va sport uchun premium krossovka. Boost texnologiyasi tufayli qo\'shimcha quvvat va yumshoqlik. Uzoq masofa yugurish va intensiv sport uchun.',
        'price': 1100000,
        'old_price': None,
        'author': 'AZIKO MARKET',
        'category': 'krossovka',
        'color': 'qora',
        'sizes': '39, 40, 41, 42, 43, 44',
        'in_stock': True,
        'is_discount': False,
        'sold_count': 43,
    },
    {
        'title': 'Reebok Classic Leather',
        'img': 'products/black-sneakers.svg',
        'review': 4,
        'description': 'Reebok Classic Leather — retro uslubdagi klassik krossovka. Teri va to\'qima yuzi, qulay taglik. Kundalik kiyim va casual uslub uchun timeless tanlov.',
        'price': 590000,
        'old_price': 699000,
        'author': 'AZIKO MARKET',
        'category': 'krossovka',
        'color': 'oq',
        'sizes': '38, 39, 40, 41, 42, 43',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 71,
    },
    # Maishiy texnika
    {
        'title': 'Philips Air Fryer HD9200',
        'img': 'products/microwave-oven.svg',
        'review': 5,
        'description': 'Philips Air Fryer HD9200 — yog\'siz qovurish texnikasi. Vitaminlar va ta\'mni saqlagan holda tez tayyorlaydi. Salomatliqni kuzatuvchilar va oila uchun ajoyib tanlov.',
        'price': 1890000,
        'old_price': 2100000,
        'author': 'AZIKO MARKET',
        'category': 'maishiy texnika',
        'color': 'oq',
        'sizes': '4.1L',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 34,
    },
    {
        'title': 'Bosch Blender MMB2111M',
        'img': 'products/microwave-oven.svg',
        'review': 4,
        'description': 'Bosch Blender MMB2111M — aralashtirgich. Smoothie, sho\'rva, meva sharbati va bolalar ovqatini tayyorlash uchun qulay. 600W, 1.5L stakani, oson tozalanadi.',
        'price': 590000,
        'old_price': None,
        'author': 'AZIKO MARKET',
        'category': 'maishiy texnika',
        'color': 'oq',
        'sizes': '1.5L',
        'in_stock': True,
        'is_discount': False,
        'sold_count': 29,
    },
    {
        'title': 'Xiaomi Smart Air Purifier 4',
        'img': 'products/microwave-oven.svg',
        'review': 4,
        'description': 'Xiaomi Smart Air Purifier 4 — havo tozalagich. HEPA filtr, chang, allergen va bakteriyalarni tutib qoladi. Smart boshqaruv, sessiz ishlash. Yotoqxona va bolalar xonasi uchun ideal.',
        'price': 1250000,
        'old_price': 1490000,
        'author': 'AZIKO MARKET',
        'category': 'maishiy texnika',
        'color': 'oq',
        'sizes': '28 m²',
        'in_stock': True,
        'is_discount': True,
        'sold_count': 22,
    },
]


def add_products(apps, schema_editor):
    Product = apps.get_model('app', 'Product')
    for data in MORE_PRODUCTS:
        if not Product.objects.filter(title__iexact=data['title']).exists():
            Product.objects.create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_ai_support_operator_monitoring'),
    ]

    operations = [
        migrations.RunPython(add_products, migrations.RunPython.noop),
    ]
